-- MySQL Script generated by MySQL Workbench
-- 10/05/16 18:33:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dive-dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dive-dev` ;

-- -----------------------------------------------------
-- Schema dive-dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dive-dev` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dive-dev` ;

-- -----------------------------------------------------
-- Table `dive-dev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dive-dev`.`users` ;

CREATE TABLE IF NOT EXISTS `dive-dev`.`users` (
  `status` VARCHAR(45) NULL DEFAULT 'active' COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT 'user' COMMENT '',
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `address` TEXT NULL COMMENT '',
  `gender` VARCHAR(45) NULL COMMENT '',
  `birthdate` DATE NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `password_confirm` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
